version: '2'

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.4.0
        command: launch manager
        environment:
        - CALIPER_BIND_SUT=fabric:1.4
        - CALIPER_BENCHCONFIG=benchmarks/samples/fabric/fabcar/config.yaml
        - CALIPER_NETWORKCONFIG=fabric-go.yaml
        volumes:
        - ./caliper-benchmarks:/hyperledger/caliper/workspace
